version: "3.8"
services:
  # MySQL database service
  db:
    image: mysql:5.7
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: lesson
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - app-network

networks:
  app-network:
    driver: bridge