version: '3.1'

services:
  storybook:
    build: 
      context: .
      target: storybook
    container_name: storybook
    ports:
      - "3001:3001"
    volumes:
      - ./my-lib-ui:/usr/app

  next-app:
    links: 
      - storybook
    build: 
      context: .
      target: next-app
    container_name: next-app
    ports:
      - "3000:3000"
    volumes:
      - ./vitrine:/usr/app

