version: '3.1'

services:
  storybook:
    build: 
      context: .
      target: storybook
    container_name: storybook
    volumes:
      - ./docker/yalc:/usr/yalc
      - ./my-lib-ui:/usr/app:delegated
    ports:
      - "6000:6000"
    command: npm run storybook

  next-app:
    links: 
      - storybook
    build: 
      context: .
      target: next-app
    container_name: next-app
    volumes:
      - ./docker/yalc:/usr/yalc
      - ./vitrine:/usr/app:delegated
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run dev
    

