version: "3.8"
services:
  # PHP service
  app:
    build: ./user
    container_name: php-app
    working_dir: /var/www/
    volumes:
      - ./user:/var/www
      - ./user/vendor:/var/www/vendor
    networks:
      - app-network
    ports:
      - 9000:9000

  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: php-nginx
    ports:
      - 8000:80
    volumes:
      - ./user:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
